// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3F5RxbQquI4RY5agWuIAqow50FkjevWU',
    appId: '1:489488956698:web:e3c5ec863a739facdb40a3',
    messagingSenderId: '489488956698',
    projectId: 'seer-17007',
    authDomain: 'seer-17007.firebaseapp.com',
    storageBucket: 'seer-17007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ErZQNSD6INTVdLmAnaWGoeakACgfjIc',
    appId: '1:489488956698:android:9be9b57ef8c045fedb40a3',
    messagingSenderId: '489488956698',
    projectId: 'seer-17007',
    storageBucket: 'seer-17007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpuSBY5CO4tmjCzrfv271zUkGZnoiqzWI',
    appId: '1:489488956698:ios:16eb8e3dc976e22ddb40a3',
    messagingSenderId: '489488956698',
    projectId: 'seer-17007',
    storageBucket: 'seer-17007.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
